module.exports = {
    Help: require('../commands/Help'),
    SpyroBot: require('../commands/SpyroBot'),
    givexp: require('../commands/givexp'),
    Ban: require('../commands/ban'),
    Kick: require('../commands/kick'),
    Warn: require('../commands/Warn'),
    Infractions: require('../commands/Infractions'),
    Clear: require('../commands/Clear'),
    Crash: require('../commands/Crash'),
    Reaction: require('../commands/ReactionRole'),
    React: require('../commands/react'),
    Join: require('../commands/join'),
    Report: require('../commands/report'),
    LogsChannel: require('../commands/logsChannel'),
    QueueChannel: require('../commands/QueueChannel'),
    runTest: require('../commands/runforlife'),
    Pin: require('../commands/pin'),
    Coin: require('../commands/coin'),
    SlashCommands: require('../commands/SlashCommands'),
    InitSlash: require('../commands/InitSlash'),
    ReactionRules: require('../commands/ReactionRules'),
    ReactRules: require('../commands/reactRules'),
    RulesCommand: require('../commands/RulesCommand'),
    xp: require('../commands/xp'),
    rank: require('../commands/rank')
}
